- name: Deploy Django App from Git
  hosts: web
  become: yes

  vars:
    app_dir: /home/ec2-user/django_app
    repo_url: "https://github.com/thanukuakshaya/it-helpdesk-project.git"

  tasks:

    - name: Install required packages
      dnf:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Create virtual environment
      command: python3 -m venv {{ app_dir }}/venv
      args:
        creates: "{{ app_dir }}/venv"

    - name: Install requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

    - name: Update ALLOWED_HOSTS
      lineinfile:
        path: "{{ app_dir }}/IT_help_desk/settings.py"
        regexp: "^ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"

    - name: Run migrations
      become_user: ec2-user
      shell: |
        source {{ app_dir }}/venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate
      args:
        chdir: "{{ app_dir }}"

    - name: Start Django using Gunicorn
      become_user: ec2-user
      shell: |
        nohup {{ app_dir }}/venv/bin/gunicorn IT_help_desk.wsgi:application --bind 0.0.0.0:8000 > gunicorn.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
